### PR TITLE
Rewrite for cidrv4

### PR DESCRIPTION
**Pull request by frack113**
Hi,
I have make the easy part:

- make SigmaCidrv4ExpressionModifier as SigmaRegularExpressionModifier
- SigmaCidrv4Expression make a better regex check
- SigmaCidrv4Expression add the convert function (return allways a list)
- add 2 simple test  to test_types.py

### CODE REVIEW

**Comment by thomaspatzke** [comment]
Great one!

Looking forward for your next one, what's  about a backend for your favorite SIEM? 😉

**Comment by thomaspatzke** [comment]
I've done some tweaks, see commit 7405da0c364fcfaae6028b9db858456b66a52f79.

**Comment by frack113** [comment]
> 
> 
> I've done some tweaks, see commit [7405da0](https://github.com/SigmaHQ/sigmatools/commit/7405da0c364fcfaae6028b9db858456b66a52f79). 👍 

`remp_old = '0.0.0/8'` I thought this morning that I should check my logic, it was a good guess, I did make a mistake.

So now I have to try 

1.  Update TextQueryBackend(Backend) to handle  a convert_value_cidr()
2.  Add test_backend_base.py  2 tests `wildcard=None` and `wildcard="*"`
3.  Add a rule in test_rule.py 

Correct ?

I wish for writing rule like 
```
Detection:
   filter_private_lan|cidrv4:
     scr:
       - 10.0.0.0/8
       - 172.16.0.0/12
       - 192.168.0.0/16
```

**Comment by thomaspatzke** [comment]
> So now I have to try
> 
>     1. Update TextQueryBackend(Backend) to handle  a convert_value_cidr()
> 
>     2. Add test_backend_base.py  2 tests `wildcard=None` and `wildcard="*"`
> 
>     3. Add a rule in test_rule.py
> 
> 
> Correct ?

Yes, in the backend base classes there should be code that handles the new CIDR type similar to regular expression type, I see you've already implemented this 👍

> On https://github.com/frack113/sigmatools/tree/cidrv4_backend I am stuck with :
> `test_convert_value_cidr - AttributeError: 'NoneType' object has no attribute 'format'`

The reason is that *cidrv4_expression* is not defined in the test backend.

**Comment by frack113** [comment]
Thanks,
It works better 

- [x] test_convert_value_cidr_wildcard_none => ['mappedA=192.168.0.0/14'] 
- [x] test_convert_value_cidr_wildcard_asterisk => ['mappedA in ("192.168.\*", "192.169.\*", "192.170.\*", "192.171.\*")']
- [x] test_convert_list_cidr_wildcard_none => ['mappedA=192.168.0.0/14 or mappedA=10.10.10.0/24']
- [x] test_convert_list_cidr_wildcard_asterisk =>['mappedA in ("192.168.\*", "192.169.\*", "192.170.\*", "192.171.\*") or mappedA="10.10.10.*"']

what is convert_condition_val_re ? 
My convert_condition_val_cidrv4 only make a pass :blush:

**Pull request merged**
