### PR TITLE
My try to add SigmaCidrv4Expression

### PR DESCRIPTION
**Pull request by frack113**
Hi,
My first attempt at adding cidrv4.
It's probably not 100% correct but I think I'm not far off or not...
I added `use_asterisk` for backend that have a native ip management other than string.

Perhaps `use_asterisk` should be optional and False by default ?

### CODE REVIEW

**Comment by thomaspatzke** [comment]
Looks good so far... Thanks for your contribution!

**Comment by thomaspatzke** [comment]
Done a review now, some remarks:

* You defined a type *SigmaCidrv4Expression*, but it's currently not used (but should be).
* The modifier has the parameter *use_asterisk*, but modifiers are applied at parse time of the Sigma rule, before the backends kick in the conversion process.

The solution would be:

* The modifier should only return the *SigmaCidrv4Expression* object (like the SigmaRegularExpressionModifier).
* The expansion logic should be moved from the modifier into a processing pipeline transformation, which is applied by all backends which *don't* support CIDR matching.
* Only backends which are able to handle CIDR should see the SigmaCidrv4Expression type objects and handle them accordingly.

Feel free to adapt or I can pick this up when I'm finished my current sigmatools programming challenge 😉

**Comment by frack113** [comment]
Hi,
I have start SigmaCidrv4Expression_V2

> The modifier should only return the _SigmaCidrv4Expression_ object (like the SigmaRegularExpressionModifier).

easy part :smile:

> The expansion logic should be moved from the modifier into a processing pipeline transformation, which is applied by all backends which _don't_ support CIDR matching.

Lost in space seasons  I
I have look  `sigma\processing\transformations.py`   :disappointed_relieved:
Maybe SigmaCidrv4Expression should have a convert method like SigmaString ?

> Only backends which are able to handle CIDR should see the SigmaCidrv4Expression type objects and handle them accordingly.

Lost in space seasons  II 

> Feel free to adapt or I can pick this up when I'm finished my current sigmatools programming challenge 😉

As no one uses it, I am free to try but without success  :flushed:

**Comment by thomaspatzke** [comment]
> I have look  `sigma\processing\transformations.py`   :disappointed_relieved:

Forget about the transformation...

> Maybe SigmaCidrv4Expression should have a convert method like SigmaString ?

... Let's do it this way. Can you move the code over to the type into a convert function? I can do the backend part.

Because some Backends expand this into multiple expressions I think we need some join logic with parameterization.

**Pull request merged**
